import type { DashboardResponse } from "@/posapp/services/dashboardService";

export const createEmptyDashboard = (): DashboardResponse => ({
	enabled: true,
	sales_overview: {
		today_sales: 0,
		today_profit: 0,
		monthly_sales: 0,
		monthly_profit: 0,
	},
	daily_sales_summary: {
		period: {},
		invoice_count: 0,
		returns_count: 0,
		gross_sales: 0,
		net_sales: 0,
		returns_amount: 0,
		discount_amount: 0,
		tax_amount: 0,
		opening_amount: 0,
		opening_cash: 0,
		closing_amount: 0,
		closing_cash: 0,
		cash_collections: 0,
		card_online_collections: 0,
		other_collections: 0,
		change_given: 0,
		collections_total: 0,
		expected_cash: 0,
		actual_cash: 0,
		cash_variance: 0,
		average_invoice_value: 0,
		has_closing_snapshot: false,
		payment_methods: [],
	},
	monthly_sales_summary: {
		period: {},
		invoice_count: 0,
		returns_count: 0,
		gross_sales: 0,
		net_sales: 0,
		returns_amount: 0,
		discount_amount: 0,
		tax_amount: 0,
		opening_amount: 0,
		opening_cash: 0,
		closing_amount: 0,
		closing_cash: 0,
		cash_collections: 0,
		card_online_collections: 0,
		other_collections: 0,
		change_given: 0,
		collections_total: 0,
		expected_cash: 0,
		actual_cash: 0,
		cash_variance: 0,
		average_invoice_value: 0,
		has_closing_snapshot: false,
		payment_methods: [],
	},
	payment_method_report: {
		period: {},
		totals: {
			invoice_count: 0,
			split_invoice_count: 0,
			pending_invoice_count: 0,
			partial_invoice_count: 0,
			unpaid_invoice_count: 0,
			pending_amount: 0,
			paid_amount: 0,
			collected_amount: 0,
			cash_amount: 0,
			card_online_amount: 0,
			other_amount: 0,
		},
		method_wise: [],
		category_wise: [],
		day_wise: [],
	},
	discount_void_return_report: {
		period: {},
		totals: {
			discount_amount: 0,
			discounted_invoice_count: 0,
			return_count: 0,
			return_amount: 0,
			void_count: 0,
			void_amount: 0,
		},
		cashier_wise: [],
		top_return_items: [],
		day_wise: [],
	},
	customer_report: {
		period: {},
		summary: {
			customer_count: 0,
			repeat_customer_count: 0,
			repeat_customer_rate_pct: 0,
			invoice_count: 0,
			sales_amount: 0,
			average_basket_size: 0,
			average_purchase_frequency_days: null,
		},
		top_customers: [],
		repeat_customers: [],
		recent_customers: [],
	},
	staff_performance_report: {
		period: {},
		summary: {
			cashier_count: 0,
			invoice_count: 0,
			sales_amount: 0,
			items_sold: 0,
			average_bill: 0,
			average_items_per_invoice: 0,
			return_count: 0,
			return_amount: 0,
			discount_amount: 0,
			void_count: 0,
			void_amount: 0,
		},
		cashier_wise: [],
		top_by_invoices: [],
		risk_activity: [],
	},
	profitability_report: {
		period: {},
		summary: {
			invoice_count: 0,
			return_invoice_count: 0,
			item_line_count: 0,
			revenue: 0,
			cogs: 0,
			gross_profit: 0,
			gross_margin_pct: null,
			average_invoice_profit: 0,
		},
		item_wise: [],
		category_wise: [],
		day_wise: [],
		highlights: {
			top_profit_item: null,
			lowest_margin_item: null,
		},
	},
	branch_location_report: {
		period: {},
		summary: {
			location_count: 0,
			total_invoices: 0,
			total_sales: 0,
			total_profit: 0,
			total_stock_qty: 0,
			low_stock_total: 0,
			cashier_count: 0,
		},
		location_wise: [],
		top_items_by_location: [],
	},
	tax_charges_report: {
		period: {},
		totals: {
			invoice_count: 0,
			return_invoice_count: 0,
			taxable_amount: 0,
			invoice_total: 0,
			tax_amount: 0,
			service_charge_amount: 0,
			fee_amount: 0,
			other_charge_amount: 0,
			round_off_amount: 0,
			invoice_adjustment_amount: 0,
			total_charge_amount: 0,
		},
		tax_heads: [],
		charge_heads: [],
		day_wise: [],
		highlights: {
			top_tax_head: null,
			top_charge_head: null,
		},
	},
	sales_trend: {
		period: {},
		day_wise: [],
		week_wise: [],
		month_wise: [],
		hourly: [],
		highlights: {
			best_day: null,
			best_hour: null,
			day_growth_pct: null,
			week_growth_pct: null,
			month_growth_pct: null,
		},
	},
	item_sales_report: {
		period: {},
		items: [],
		highlights: {
			best_seller: null,
			top_margin_item: null,
			top_discount_item: null,
		},
	},
	category_brand_variant_report: {
		period: {},
		category_wise: [],
		brand_wise: [],
		variant_wise: [],
		attribute_wise: [],
		highlights: {
			top_category: null,
			top_brand: null,
			top_variant: null,
		},
	},
	inventory_status_report: {
		period: {},
		threshold: 10,
		summary: {
			total_items: 0,
			total_stock_qty: 0,
			low_stock_count: 0,
			out_of_stock_count: 0,
			negative_stock_count: 0,
			slow_moving_count: 0,
			dead_stock_count: 0,
		},
		low_stock_items: [],
		out_of_stock_items: [],
		negative_stock_items: [],
		slow_moving_items: [],
		dead_stock_items: [],
	},
	stock_movement_report: {
		period: {},
		summary: {
			movement_count: 0,
			sale_out_qty: 0,
			return_in_qty: 0,
			adjustment_in_qty: 0,
			adjustment_out_qty: 0,
			transfer_in_qty: 0,
			transfer_out_qty: 0,
			other_in_qty: 0,
			other_out_qty: 0,
			net_qty: 0,
			net_value: 0,
		},
		day_wise: [],
		recent_movements: [],
	},
	reorder_purchase_suggestions: {
		period: {},
		summary: {
			candidate_items: 0,
			suggestion_count: 0,
			critical_count: 0,
			high_count: 0,
			medium_count: 0,
			low_count: 0,
			total_suggested_qty: 0,
			estimated_purchase_value: 0,
		},
		suggestions: [],
	},
	inventory_insights: {
		fast_moving_items: [],
		fast_moving_period: {
			from: "",
			to: "",
			days: 0,
		},
		fast_moving_pagination: {
			page: 1,
			page_size: 10,
			total_count: 0,
			total_pages: 0,
			search: "",
		},
		low_stock_items: [],
		low_stock_threshold: 10,
	},
	supplier_overview: {
		summary: {
			supplier_count: 0,
			purchase_count: 0,
			purchase_amount: 0,
			paid_amount: 0,
			pending_amount: 0,
			avg_invoice_value: 0,
			pending_ratio_pct: 0,
		},
		purchase_summary: [],
		risk_suppliers: [],
		day_wise: [],
		highlights: {
			top_supplier: null,
			top_pending_supplier: null,
		},
		period: {},
	},
});

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function deepMergeDashboard<T>(base: T, payload: unknown): T {
	if (!isPlainObject(base) || !isPlainObject(payload)) {
		return (payload === undefined ? base : payload) as T;
	}

	const merged: Record<string, unknown> = { ...base };
	Object.entries(payload).forEach(([key, value]) => {
		const baseValue = (base as Record<string, unknown>)[key];
		merged[key] = isPlainObject(baseValue) && isPlainObject(value)
			? deepMergeDashboard(baseValue, value)
			: value;
	});
	return merged as T;
}

export function mergeDashboardPayload(payload?: Partial<DashboardResponse>): DashboardResponse {
	const base = createEmptyDashboard();
	return deepMergeDashboard(base, payload || {});
}
